### ISSUE TITLE
Optimized find thresholds is optimized to crash

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/AMP#37]
Currently the new version of the optimize KNN thresholds crashes after being selected.

This was tested after running the regular KNN, selecting an image, getting the plots displayed, and then re-running

**Comment by ackagel** [comment]
Not able to reproduce this on my end.  I'll add the error logging system and hopefully (or not hopefully?) this will rear its head again and we'll see what the problem is.

**Comment by ngreenwald** [comment]
Gotcha little guy 
![image](https://user-images.githubusercontent.com/13770365/122467920-ec6fc700-cf6f-11eb-8e67-d607eeb83df9.png)

**Comment by ackagel** [comment]
apparently this is happening only for the 'Background' channel in the ark-analysis example data.  If this happens on an important channel, I'll look into it more, but for now, I'm going to catch+display the error and then continue running the optimizations for other channels/points instead of crashing.
